<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <InvariantGlobalization>true</InvariantGlobalization>
    <Product>ProxyServerSharp</Product>
    <Company>ProxyServerSharp</Company>
    <Version>2.0.0</Version>
    <Copyright>Copyright (c) Brandon Scott</Copyright>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

</Project>
